### ISSUE TITLE
Allow/support multiple media types for a resource with a single PID?

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/pid4cat-model#12]
The doi system allows to specify multiple [media types](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types) for each PID (see DataCite [MDS API](https://support.datacite.org/reference/list-media-for-doi-name)). Therefore, the same PID may be used to access the html landing page (media type "text/html") but also the pdf (media type "application/pdf").

In the PID record, we already have a field to reference to an rdf-representation of the resource. This was already part of the first public version.

But should PID4Cat also support other media type in a general way? Practically, this would mean to add a another field to the metadata schema that stores a list of (media-type, url) pairs.

Currently I am slightly in favor of adding it. @prestonrodrigues @markdoerr & anyone interested: What are your thoughts?

**Comment by dalito** [comment]
FYI: The handle system does not support content negotiation on its own. For DOIs datacite implements this functionality in doi.org. If DOIs are accessed as handles, content negotiation is also not available/usable.

**Comment by markdoerr** [comment]
Hi @dalito,
I also  think, adding a list of available media types for a resource is a good idea.
Even if @prestonrodrigues will not manage to implement the content negotiation in the API 2.0, he might mange to implement it in future. We could set the field MEDIA_TYPES  : ["[application/json](https://www.iana.org/assignments/media-types/application/json)"] as a list with only one entry as default for now.
