### ISSUE TITLE
Feat: Add "Dataservice" to ResourceCategory enum

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/pid4cat-model#20]
Currently software services or tools are not reflected well in the resource categories.

@HendrikBorgelt suggested to add "Data Service" (meaning as in [DCAT](https://www.w3.org/TR/vocab-dcat-3/#Class:Data_Service)) as to the ResourceCategory enum.

**Comment by markdoerr** [comment]
I think, it is a good idea.
