### ISSUE TITLE
API-2.0-preparation: final review of record "types" (names)

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/pid4cat-model#22]
Review record "types" (names) for the ["rows" in the handle record](https://github.com/nfdi4cat/pid4cat-model/blob/main/nfdi4cat_details.md#mapping-of-pid4cat-schema-to-handle-record). Since the names will be used for API-endpoint names they should ideally not change once in use.

- [x] remove slot "record_version"
- [x] ...more? - Yes, see linked PR.

**Comment by markdoerr** [comment]
From my perspective it look nice now. We should test in practice.

Shall we create a new release of this model and ask Preston (@prestonrodrigues ) to implement it  for a test ?

**Comment by dalito** [comment]
@markdoerr Thanks for having another look! I also think it is structurally ready (adding mappings #19 would not change the json-serialisation).

There ies only one part that I am still thinking about: Should we model ResourceInfo differently to support various representations? #12

In principle, this would mean replacing "hardcoded media-type slots"

```
  ResourceInfo:
    slots:
      (...)
      - rdf_url
      - rdf_type
      - schema_url
      - schema_type
```
By a link to a class that models alternative representations
```
class:
    AlternateRepresentation:
    - mime_type
    - url
```

I think that we should change this so will create a PR. Comments? @HendrikBorgelt @prestonrodrigues

**Comment by markdoerr** [comment]
@dalito, 
I like your proposal - but please use the term "media_type" or "iana_type" (MIME type is deprecated) and add a link to the [IANA specification](https://www.iana.org/assignments/media-types/media-types.xhtml) in the class definition.

**Comment by dalito** [comment]
For an extended API, adapting [Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/) could be interesting (in far future 😉 ).
