### ISSUE TITLE
Add example data for testing API-2.0

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/pid4cat-model#24]
Currently the example data are only using some features of the pid4cat model. 

For testing the API-2.0 and for showcasing our approach we need also examples that use all features.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the existing PID4CatRecord-001.yaml example to include more features and created a new PID4CatRecord-002.yaml example that uses all features of the pid4cat model.

You can review changes in this commit: https://github.com/mnmnk43434/nfdi4cat-pid4cat-model-24/commit/f2b779bfda338e50bc12e8ba06257f37fbec9437.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by dalito** [comment]
@prestonrodrigues - Please have a look at #24.

It adds a rich example to the examples folder (`json` and Python scripts). Let me know if you need more, e.g. `json` split up by handle record "row".
